# ollama-deployment/overlays/multiple-models/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vllm-gpu

resources:
  - ../base
patches:
  - patch-deployment.yaml

