# patch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  template:
    spec:
      containers:
      - name: server
        args:
        - "--model"
        - "mistralai/Mistral-7B-Instruct-v0.2"
        - "--download-dir"
        - "/models-cache"
        - "--dtype"
        - "float16"
        - "--max-model-len"
        - "6144"