# patch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  template:
    spec:
      containers:
      - name: server
        args:
        - "--model"
        - "BigCode/micro-HiPPO-v2.4.2b-315M"
        - "--download-dir"
        - "/models-cache"
        - "--dtype"
        - "float16"
        - "--max-model-len"
        - "2048"
