apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: financial-fraud-detection-system

resources:
  - ../../base
  - kafka-cluster.yaml
  - kafdrop-dc.yaml
  - kafdrop-service.yaml
  - kafdrop-route.yaml

patches:
  - target:
      kind: Kafka
      name: kafka-cluster
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: financial-fraud-detection-system
      - op: replace
        path: /metadata/name
        value: kafka
  - target:
      kind: Namespace
      name: my-project
    patch: |-
      - op: replace
        path: /metadata/name
        value: financial-fraud-detection-system