- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: amq-streams-operator
        path: components/operators/amq-streams/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: camel-k-operator
        path: components/operators/camel-k-operator/overlays/1.10.x
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: ollama-server
        path: components/llm-servers/ollama/gitops/overlays
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: cert-manager
        path: components/operators/cert-manager