kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ecommerce-personalization-engine
  namespace: ecommerce-personalization-engine
  labels:
    app: ecommerce-personalization-engine
    app.kubernetes.io/component: ecommerce-personalization-engine
    app.kubernetes.io/instance: ecommerce-personalization-engine
    app.kubernetes.io/name: ecommerce-personalization-engine
    app.kubernetes.io/part-of: ecommerce-personalization-engine
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ecommerce-personalization-engine:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/VectorStream/vector-stream-utils.git'
    contextDir: ecommerce_personalization_engine
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: ecommerce-personalization-engine-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: ecommerce-personalization-engine-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
