kind: Service
apiVersion: v1
metadata:
  name: ecommerce-personalization-engine
  namespace: ecommerce-personalization-engine
  labels:
    deployment: ecommerce-personalization-engine
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8000-tcp
      protocol: TCP
      port: 8000
      targetPort: 8000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: ecommerce-personalization-engine
