kind: Deployment
apiVersion: apps/v1
metadata:
  name: ecommerce-personalization-engine
  namespace: ecommerce-personalization-engine
  labels:
    app: ecommerce-personalization-engine
    app.kubernetes.io/component: ecommerce-personalization-engine
    app.kubernetes.io/instance: ecommerce-personalization-engine
    app.kubernetes.io/name: ecommerce-personalization-engine
    app.kubernetes.io/part-of: ecommerce-personalization-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-personalization-engine
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ecommerce-personalization-engine
        deployment: ecommerce-personalization-engine
    spec:
      containers:
        - name: ecommerce-personalization-engine
          image: >-
            image-registry.openshift-image-registry.svc:5000/ecommerce-personalization-engine/ecommerce-personalization-engine:latest
          env:
            - name: KAFKA_BROKER
              value: >-
                kafka-kafka-bootstrap.ecommerce-personalization-engine.svc.cluster.local:9092
            - name: KAFKA_TOPIC_BROWSING
              value: comic_book_browsing
            - name: KAFKA_TOPIC_PURCHASES
              value: comic_book_purchases
            - name: INTERACTION_INTERVAL
              value: '5'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
