kind: Service
apiVersion: v1
metadata:
  name: smart-city-traffic-management
  namespace: smart-city-traffic-management
  labels:
    deployment: smart-city-traffic-management
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8000-tcp
      protocol: TCP
      port: 8000
      targetPort: 8000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: smart-city-traffic-management
