kind: Deployment
apiVersion: apps/v1
metadata:
  name: smart-city-traffic-management
  namespace: smart-city-traffic-management
  labels:
    app: smart-city-traffic-management
    app.kubernetes.io/component: smart-city-traffic-management
    app.kubernetes.io/instance: smart-city-traffic-management
    app.kubernetes.io/name: smart-city-traffic-management
    app.kubernetes.io/part-of: smart-city-traffic-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-city-traffic-management
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: smart-city-traffic-management
        deployment: smart-city-traffic-management
    spec:
      containers:
        - name: smart-city-traffic-management
          image: >-
            image-registry.openshift-image-registry.svc:5000/smart-city-traffic-management/smart-city-traffic-management:latest
          env:
            - name: KAFKA_BROKER
              value: >-
                kafka-kafka-bootstrap.smart-city-traffic-management.svc.cluster.local:9092
            - name: INTERVAL
              value: "10"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
