apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: redis-rag-
  name: redis-rag-dt6pt
  namespace: redis-rag
spec:
  targetNamespaces:
    - redis-rag
  upgradeStrategy: Default
