# patch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  template:
    spec:
      containers:
      - name: server
        args:
        - "--model"
        - "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
        - "--download-dir"
        - "/models-cache"
        - "--max-model-len"
        -  "2048"
