# patch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  template:
    spec:
      containers:
      - name: server
        args:
        - "--model"
        - "nvidia/Llama-3.1-Nemotron-70B-Instruct"
        - "--download-dir"
        - "/models-cache"
        - "--dtype"
        - "float16"
        - "--max-model-len"
        - "2048"
