---
apiVersion: apps/v1
kind: Deployment
meta
  name: vllm
spec:
  template:
    spec:
      containers:
        - name: model-server
          resources:
            limits:
              cpu: 10
              memory: 20Gi
            requests:
              cpu: 10
              memory: 20Gi
