apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redb
  namespace: redis-rag
spec:
  memorySize: 500MB
  persistence: snapshotEvery12Hour
  modules:
    - name: search
      version: "2.4.0"
