apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redb-rag-instance
  namespace: redis-rag
spec:
  defaultUser: true
  memorySize: 300MB
  modulesList:
    - name: ReJSON
      version: 2.4.9
    - name: search
      version: 2.8.19
