apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "pgvector"

resources:
  #- namespace.yaml
  - scc.yaml
  - operator_group.yaml
  - subscription.yaml
  - redis_cluster.yaml
  - database_instance.yaml