kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: financial-fraud-detection-system
  namespace: financial-fraud-detection-system
  labels:
    app: financial-fraud-detection-system
    app.kubernetes.io/component: financial-fraud-detection-system
    app.kubernetes.io/instance: financial-fraud-detection-system
    app.kubernetes.io/name: financial-fraud-detection-system
    app.kubernetes.io/part-of: financial-fraud-detection-system
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'financial-fraud-detection-system:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/VectorStream/vector-stream-utils.git'
    contextDir: financial_fraud_detection_system
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: financial-fraud-detection-system-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: financial-fraud-detection-system-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
